using System.Collections.Generic;
using System.Text;
using Fund.Infrastructure.RepoGenerator.Models;

namespace Fund.Infrastructure.RepoGenerator.Emitters;

internal static class DataInitializerEmitter
{
    public static string Emit(
        IReadOnlyList<EntityModel> entities)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine();

        sb.AppendLine("namespace Fund.Infrastructure.SimpleSqlSourceGenerated;");
        sb.AppendLine();

        sb.AppendLine("public class DbDataInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    public static void DataInit(DbConnection dbConnection)");
        sb.AppendLine("    {");
        sb.AppendLine("        dbConnection.Open();");
        sb.AppendLine();
        sb.AppendLine("        using var command = dbConnection.CreateCommand();");
        sb.AppendLine();

        foreach (var entity in entities)
        {
            sb.AppendLine(
                $"        command.CommandText = {entity.Name}Extension.GetInitCommand();");

            sb.AppendLine(
                "        command.ExecuteNonQuery();");

            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}