using System.Collections.Generic;
using System.Text;
using Fund.Infrastructure.RepoGenerator.Models;

namespace Fund.Infrastructure.RepoGenerator.Emitters;

internal static class DependencyInjectionEmitter
{
    private const string RepositoryMetadataName =
        "Fund.Core.Repositories.IRepository";

    public static string Emit(
        IReadOnlyList<EntityModel> entities)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine(
            "using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        sb.AppendLine(
            "namespace Fund.Infrastructure.SimpleSqlSourceGenerated;");

        sb.AppendLine();

        sb.AppendLine(
            "internal static class RepositoryDependencyInjection");

        sb.AppendLine("{");

        sb.AppendLine(
            "    public static void AddGeneratedRepositories(this");

        sb.AppendLine(
            "        IServiceCollection services)");

        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            sb.Append(
                "        services.AddScoped<");

            sb.Append(
                "global::");

            sb.Append(
                RepositoryMetadataName);

            sb.Append("<");

            sb.Append(
                entity.FullyQualifiedName);

            sb.Append(">, ");

            sb.Append(
                entity.Name);

            sb.Append(
                "Repository");

            sb.AppendLine(">();");
        }

        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }
}