using System.Collections.Generic;
using System.Text;
using Fund.Infrastructure.RepoGenerator.Models;

namespace Fund.Infrastructure.RepoGenerator.Emitters;

internal static class RepositoryEmitter
{
    public static string Emit(
        EntityModel entity)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using Fund.Infrastructure;");
        sb.AppendLine();

        sb.AppendLine(
            "namespace Fund.Infrastructure.SimpleSqlSourceGenerated;");

        sb.AppendLine();

        sb.Append("internal sealed class ");
        sb.Append(entity.Name);
        sb.AppendLine(
            "Repository : RepositoryBase<");

        sb.Append(entity.FullyQualifiedName);

        sb.AppendLine(">");

        sb.AppendLine("{");

        sb.AppendLine();

        sb.AppendLine(
            "    public " +
            entity.Name +
            "Repository(FundDbContext context)");

        sb.AppendLine(
            "        : base(context)");

        sb.AppendLine("    {");
        sb.AppendLine("    }");

        sb.AppendLine();

        GenerateTableName(
            sb,
            entity);

        GenerateSelectColumns(
            sb,
            entity);

        GenerateMap(
            sb,
            entity);

        GenerateInsertCommand(
            sb,
            entity);

        GenerateUpdateCommand(
            sb,
            entity);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateTableName(
        StringBuilder sb,
        EntityModel entity)
    {
        sb.Append(
            "    protected override string TableName => \"");

        sb.Append(entity.Name);

        sb.AppendLine("\";");

        sb.AppendLine();
    }

    private static void GenerateSelectColumns(
        StringBuilder sb,
        EntityModel entity)
    {
        sb.AppendLine(
            "    protected override string SelectColumns => \"\"\"");

        for (var i = 0;
             i < entity.Properties.Count;
             i++)
        {
            var property =
                entity.Properties[i];

            sb.Append("        ");
            sb.Append(property.Name);

            if (i < entity.Properties.Count - 1)
                sb.Append(',');

            sb.AppendLine();
        }

        sb.AppendLine("        \"\"\";");

        sb.AppendLine();
    }

    private static void GenerateMap(
        StringBuilder sb,
        EntityModel entity)
    {
        sb.Append(
            "    protected override ");

        sb.Append(
            entity.FullyQualifiedName);

        sb.AppendLine(
            " Map(DbDataReader reader)");

        sb.AppendLine("    {");

        sb.AppendLine(
            "        return new " +
            entity.FullyQualifiedName +
            "()");

        sb.AppendLine("        {");

        for (var i = 0;
             i < entity.Properties.Count;
             i++)
        {
            var property =
                entity.Properties[i];

            sb.Append("            ");
            sb.Append(property.Name);
            sb.Append(" = ");

            sb.Append(
                GenerateReaderExpression(
                    property,
                    i));

            sb.AppendLine(",");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");

        sb.AppendLine();
    }

    private static string GenerateReaderExpression(
        PropertyModel property,
        int index)
    {
        var value =
            GenerateNonNullableReaderExpression(
                property,
                index);

        if (!property.IsNullable)
            return value;

        return
            $"reader.IsDBNull({index}) " +
            $"? null : {value}";
    }

    private static string GenerateNonNullableReaderExpression(
        PropertyModel property,
        int index)
    {
        return property.UnderlyingType switch
        {
            "string" =>
                $"reader.GetString({index})",

            "int" =>
                $"reader.GetInt32({index})",

            "long" =>
                $"reader.GetInt64({index})",

            "short" =>
                $"reader.GetInt16({index})",

            "byte" =>
                $"reader.GetByte({index})",

            "bool" =>
                $"reader.GetBoolean({index})",

            "double" =>
                $"reader.GetDouble({index})",

            "float" =>
                $"reader.GetFloat({index})",

            "decimal" =>
                $"reader.GetDecimal({index})",

            "System.DateTime" =>
                $"reader.GetDateTime({index})",

            "System.DateTimeOffset" =>
                $"System.DateTimeOffset.Parse(" +
                $"reader.GetString({index}))",

            "System.Guid" =>
                $"System.Guid.Parse(" +
                $"reader.GetString({index}))",

            _ =>
                $"reader.GetFieldValue<" +
                $"{property.UnderlyingType}>({index})"
        };
    }

    private static void GenerateInsertCommand(
        StringBuilder sb,
        EntityModel entity)
    {
        sb.AppendLine(
            "    protected override DbCommand " +
            "CreateInsertCommand(");

        sb.AppendLine(
            "        DbConnection connection,");

        sb.Append("        ");
        sb.Append(entity.FullyQualifiedName);
        sb.AppendLine(" entity)");

        sb.AppendLine("    {");

        sb.AppendLine(
            "        var command = " +
            "connection.CreateCommand();");

        sb.AppendLine();

        sb.AppendLine(
            "        command.CommandText = \"\"\"");

        sb.Append(
            "            INSERT INTO ");

        sb.AppendLine(entity.Name);

        sb.AppendLine(
            "            (");

        for (var i = 0;
             i < entity.Properties.Count;
             i++)
        {
            var property =
                entity.Properties[i];

            sb.Append("                ");
            sb.Append(property.Name);

            if (i < entity.Properties.Count - 1)
                sb.Append(',');

            sb.AppendLine();
        }

        sb.AppendLine(
            "            )");

        sb.AppendLine(
            "            VALUES");

        sb.AppendLine(
            "            (");

        for (var i = 0;
             i < entity.Properties.Count;
             i++)
        {
            var property =
                entity.Properties[i];

            sb.Append("                @");
            sb.Append(property.Name);

            if (i < entity.Properties.Count - 1)
                sb.Append(',');

            sb.AppendLine();
        }

        sb.AppendLine(
            "            )");

        sb.AppendLine(
            "            \"\"\";");

        sb.AppendLine();

        GenerateParameters(
            sb,
            entity.Properties);

        sb.AppendLine(
            "        return command;");

        sb.AppendLine("    }");

        sb.AppendLine();
    }

    private static void GenerateUpdateCommand(
        StringBuilder sb,
        EntityModel entity)
    {
        sb.AppendLine(
            "    protected override DbCommand " +
            "CreateUpdateCommand(");

        sb.AppendLine(
            "        DbConnection connection,");

        sb.Append("        ");
        sb.Append(entity.FullyQualifiedName);
        sb.AppendLine(" entity)");

        sb.AppendLine("    {");

        sb.AppendLine(
            "        var command = " +
            "connection.CreateCommand();");

        sb.AppendLine();

        sb.AppendLine(
            "        command.CommandText = \"\"\"");

        sb.Append(
            "            UPDATE ");

        sb.AppendLine(entity.Name);

        sb.AppendLine(
            "            SET");

        for (var i = 0;
             i < entity.NonIdProperties.Count;
             i++)
        {
            var property =
                entity.NonIdProperties[i];

            sb.Append("                ");
            sb.Append(property.Name);
            sb.Append(" = @");
            sb.Append(property.Name);

            if (i < entity.NonIdProperties.Count - 1)
                sb.Append(',');

            sb.AppendLine();
        }

        sb.AppendLine(
            "            WHERE Id = @Id");

        sb.AppendLine(
            "            \"\"\";");

        sb.AppendLine();

        GenerateParameters(
            sb,
            entity.Properties);

        sb.AppendLine(
            "        return command;");

        sb.AppendLine("    }");

        sb.AppendLine();
    }

    private static void GenerateParameters(
        StringBuilder sb,
        IReadOnlyList<PropertyModel> properties)
    {
        foreach (var property in properties)
        {
            sb.Append("        AddParameter(");
            sb.Append("command, \"@");
            sb.Append(property.Name);
            sb.Append("\", entity.");
            sb.Append(property.Name);
            sb.AppendLine(");");
        }

        sb.AppendLine();
    }
}